### ISSUE TITLE
Improving BibTeX input & output

### ISSUE THREAD

**Issue by larsgw** [larsgw/citation.js#17]
Currently most test cases work, but some things don't (see example below). I'll be working on:
- Better use of field value delimiters, e.g. `{`, `{{` or `"`
- Move property parsing (BibTeX->CSL) to separate function, just as with Wikidata props
- Move reversed prop parsing (CSL->BibTeX) to separate function as well
- Improve prop parsing in both directions, if I can find good documentation

If someone has good documentation, that'd be really helpful.

# Tasks

- [x] BibTeX string parser
- [x] BibTeX-JSON property parser
- [x] BibTeX-JSON property getter

# Examples
- [x] The year field isn't working when imported in Mendeley (although it [works](http://www.citeulike.org/user/egonw/article/14173713) in CiteULike). https://gist.github.com/larsgw/73d1e8fce01e0239d38ce1c599a81ccb

**Comment by larsgw** [comment]
I'll take a look at the [Zotero BibTeX Translator](https://github.com/zotero/translators/blob/master/BibTeX.js) as [suggested here](https://twitter.com/rintzezelle/status/792738660282236928). I'd rather be able to parse BibTeX without external libraries, so perhaps I can reverse-engineer some BibTeX fields from the translator. The output is currently pretty good anyway, but there's always room for improvement.

**Comment by larsgw** [comment]
The mendelev error was seen on desktop `v1.17.2` but doesn't reproduce on all versions. About the BibTeX to BibTeX-JSON parser: I currently have a `while` loop parser in testing. I still have to figure some things out regarding escaped characters and not having an infinite loop when the syntax is incorrect.

**Comment by larsgw** [comment]
Syntax error are now handled. I still need to recognise and unescape tokens.
